export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";

